baseURL = 'https://nether-skin.github.io/'
languageCode = 'en-us'
title = 'Nether Skin'
theme = ["nether-theme", "hugo-cite"]
sectionPagesMenu = "main"
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      # autoHeadingID = true
      # autoHeadingIDType = 'github'
      # wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true
[outputs]
  home = ['HTML', 'RSS']
  page = ['HTML']
  # term = ['HTML', 'JSON', 'RSS']
  # taxonomy = ['json']
# ignoreErrors = ["error-output-taxonomy"] 
