baseURL = 'https://nether-skin.github.io/'
languageCode = 'en-us'
title = 'Nether Skin'
theme = ["nether-theme", "hugo-cite"]
sectionPagesMenu = "main"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
